#language: php
#
#sudo: false
#
#cache:
#    directories:
#        - $HOME/.composer/cache/files
#
#matrix:
#    fast_finish: true
#    include:
#        - php: 7.2
#          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak_vendors"
#        #- php: 7.1
#          #env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak_vendors"
#        #- php: 7.1
#        - php: 7.2
#          env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"
#        #- php: 7.2
#          #env: DEPENDENCIES="symfony/lts:^2"
#        - php: 7.2
#          env: DEPENDENCIES="symfony/lts:^3" COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
#        - php: 7.2
#          env: STABILITY="dev"
#    allow_failures:
#        - env: STABILITY="dev"
#
#before_install:
#    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
#    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
#    - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;
#
#install:
#    - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --prefer-dist --no-interaction --prefer-stable --quiet; fi
#    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
#    - composer require symfony/console
#    - composer require symfony/messenger
#
#script:
#    - ./vendor/bin/phpunit


language: php

php:
    - 7.2
    - 7.3
    - 7.4snapshot
    - nightly


cache:
    directories:
        - $HOME/.composer/cache

matrix:
    fast_finish: true
    include:
        - php: 7.2
          env: SYMFONY_VERSION=3.4.* COMPOSER_FLAGS="--prefer-dist --prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 7.2
          env: SYMFONY_VERSION=4.3.*

        - php: 7.3
          env: SYMFONY_VERSION=4.2.*

        - php: 7.3
          env: SYMFONY_VERSION=4.3.*

    allow_failures:
        - php: nightly

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=weak
        - COMPOSER_FLAGS="--prefer-dist"


before_script:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update $COMPOSER_FLAGS --no-interaction